### ISSUE TITLE
_configManager.GetConfigurationAsync().Result causing deadlock situation in OpenIdConnectCachingSecurityTokenProvider.cs file

### ISSUE THREAD

**Issue by John12x** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#11]
Below code is like calling an async method in sync context which is a bad practice and causing deadlock with infinite loops.

            _synclock.EnterWriteLock();  --> synchronous lock

                OpenIdConnectConfiguration config = _configManager.GetConfigurationAsync().Result;  --> async method

Could you please update the above code as below to avoid a deadlock situation.

                OpenIdConnectConfiguration config =Task.Run( _configManager.GetConfigurationAsync).Result;

**Comment by mvrak** [comment]
There is some sample code that wasn't designed with scalability in mind.  Thank you for pointing this out.  We are creating tasks to update samples when we find this.
