### ISSUE TITLE
OAuthBearerAuthenticationOptions in .NET 4.6 with Azure AD v2

### ISSUE THREAD

**Issue by jrmcdona** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#15]
Do you guys have a sample in .NET 4.6 or can give a pointer?

IIssuerSecurityTokenProvider is not longer available in Microsoft.Owin.Security.Jwt. There is now IIssuerSecurityKeyProvider and OpenIdConnectCachingSecurityTokenProvider is no longer compiling.

Therefore I cannot get OAuthBearerAuthenticationOptions working with an Azure AD v2 endpoint on my Web API.

**Comment by mvrak** [comment]
Can you move this issue to the Owin, Wilson, or MSAL.net repos? I think samples there may cover your need.

Example:
https://github.com/AzureAD/microsoft-authentication-library-for-dotnet
