### ISSUE TITLE
Please offer guidance for ADFS + OpenID Connect

### ISSUE THREAD

**Issue by oising** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#16]
I have been searching for hours and am unable to find clear guidance on how to use ADAL.js with ADFS (v4+ with openid connect) with a SPA. Please provide some kind of translation matrix for parameters and configuration values to allow use to use ADFS in the place of AAD. 

You make it a point to claim ADFS compatibility but make it very hard for the rest of us to verify this statement.

**Comment by mvrak** [comment]
By interacting with AAD you get ADFS compatibility.  Can you detail your scenario more?  Maybe I can provide some sample flow.

Also [see here](https://github.com/AzureAD/microsoft-authentication-library-for-dotnet/wiki/ADFS-support),  where for .NET we cover more of the rationale.

> MSAL.NET supports talking to Azure AD, which itself signs-in managed users (users managed in Azure AD), or federated users (users managed by another identity provider, which, in the case we are interested is federated through ADFS). MSAL.NET does not know about the fact that users are federated. As far as it’s concerned, it talks to Azure AD.
The authority you'll use in the case is the usual authority (common, or organizations, or tenanted)

**Comment by oising** [comment]
@mvrak The problem is that you guys seem to assume (or want to push for the $$$ angle) that AAD is the answer to everything. If someone has a home rolled authorization model and just wants to plug in an identity solution, i.e. use a client's ADFS as an IDP , then AAD doesn't - and shouldn't -- come into the equation. AAD is a heavyweight and costly authorization and authentication solution. OpenID Connect was expressly designed to remove the authorization part of OAuth2 (e.g. resource) from the recipe. 

The sample we'd like to see is a SPA (e.g. angular app) with a node backend that uses ADFS as a pure IDP only. It would use the implicit flow, and only needs an id_token. This token would need to be verified against the signing keys in ADFS, on the server (node) side as well as the client side. No SAML. No federation. No AAD. Just OpenID connect, and jwt.verify, with ADFS 4+. 

And also, please explain why Microsoft enables CORS support on the .well-known/openid-configuration endpoint, but does not enable it on the keys endpoint. This makes it pretty pointless, since openid compliant client-side libraries expect to the validate the jwt on the client side too, which they cannot do because the keys endpoint doesn't support CORS. For what it's worth, I get the point you're trying to make with blocking CORS on keys (the browser should not be trusted to validate tokens destined for a server endpoint), but frankly, the openid library authors don't seem to care.

**Comment by mvrak** [comment]
@oising, I think I understand what you mean, and I don't think it is supported.  I think of AAD as the source for OIDC compatibility.  The ADFS integration that another company might implement doesn't automatically make them OIDC compliant "directly".  They could do other work to expose something that would be.   

Stated another way:  ADAL.js provides inter-operability with AAD, which then has compatibility to redirect to other protocols.  ADAL.js doesn't itself work that other magic until AAD is involved.

When I mention ADFS compatibility, what I am thinking is that our library would open a window displaying an AAD interface.  The ADFS compatibility only comes from AAD recognizing the user/tenant and providing an internal redirect.   The window/auth flow would have no idea what ADFS to access without AAD providing a lookup and redirect information.

I hope that answers your first question.  
As to your second question regarding CORS, I'll need to learn more myself before I can comment.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
