### ISSUE TITLE
 Ida::Tenant not required: No longer the case. Solution.

### ISSUE THREAD

**Issue by Didjeeh** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#17]
You will get following exception on trying to authenticate with (in my case) an organization account.

AADSTS50194: Application 'cab0646e-fd4e-4ea9-8eae-68e057d6bf2e'(Azure-Samples_active-directory-javascript-singlepageapp-dotnet-webapi-v2) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

If you have the same problem you can do the following:

Find the TenantId on the overview of your registered app:

![image](https://user-images.githubusercontent.com/46340164/59095549-1883f680-8919-11e9-8c77-cc5a848bc362.png)

Then do the following in code:

![image](https://user-images.githubusercontent.com/46340164/59095335-79f79580-8918-11e9-97a9-f8df409502a3.png)

![image](https://user-images.githubusercontent.com/46340164/59095629-4cf7b280-8919-11e9-8fd5-bff68bc824c8.png)

![image](https://user-images.githubusercontent.com/46340164/59096123-7533e100-891a-11e9-8b08-70ed0efbfe11.png)

**Comment by mvrak** [comment]
Hey Didjeeh, thank you for your feedback and solution.  If I'm reading this correctly, you: 
1) replaced the ida:Audience value with xxxx in Web.config, and
2) added the clientID key with value ApplicationId to window.config in StartupAuth.cs.

Is this correct?  If so I'll get it validated.

Thanks

**Comment by mvrak** [comment]
Hello Didjeeh,

After looking at this, I'm going to classify it as "undefined" behavior they may stop working in later releases.  I don't see a reason to patch it out so I'm not recommending any action, and I don't think I would include it in a faq.   Thank you for analyzing it though!

**Comment by Didjeeh** [comment]
Hi mvarek,

Thanks for the follow up!

> * replaced the ida:Audience value with xxxx in Web.config, and
> * added the clientID key with value ApplicationId to window.config in StartupAuth.cs.

Those are not important. I just refactored the code a bit.

The tenant id is the one that is important (error code AADSTS50194), as stated in my first comment here.
