### ISSUE TITLE
Using msal.js on SharePoint online classic page gives error SCRIPT5009: 'Map' is undefined msal.min.js

### ISSUE THREAD

**Issue by kavitajoshi** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#18]
We are using Azure AD app and msal.js to connect to Yammer in SharePoint online. The connection and script works fine in Chrome but in IE it gives error and msal.js is not loaded. The SharePoint online site is based on classic team site template so IE mode is IE 10 and loading the page gives error SCRIPT5009: 'Map' is undefined msal.min.js (17,68667).

**Comment by mvrak** [comment]
Hello Kavita,  Thank you for your interest!  We test against IE11, and we have [this page to discuss IE](https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Using-msal.js-with-Internet-Explorer) quirks.

Against IE10 I'm not sure.  There are probably some simple compatibility hacks you could try, however we don't have a plan to support that.  How much of your audience is expected to be IE10?  

Thanks!

**Comment by kavitajoshi** [comment]
Hello Amit,

Thanks for your reply. The IE users are using IE 11, but the site renders in IE10 mode as the site is SharePoint Online site based of classic team site template. And all SharePoint classic site has meta http-equiv="X-UA-Compatible" content="IE=10" in master page.

**Comment by kavitajoshi** [comment]
Hello @mvrak
I'm able to resolve IE issue by using another polyfill for IE instead of bluebird.js mentioned on https://github.com/AzureAD/microsoft-authentication-library-for-js/wiki/Using-msal.js-with-Internet-Explorer

I'm referencing https://unpkg.com/core-js-bundle@3.0.1/minified.js instead.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
