### ISSUE TITLE
Unhandled rejection AADSTS700054: response_type 'id_token' is not enabled for the application.

### ISSUE THREAD

**Issue by maggix** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#23]
Hello, 
trying to run the sample code against Azure AD B2C returns the error: 

```
Unhandled rejection AADSTS700054: response_type 'id_token' is not enabled for the application.
```

The reasons seems to be that Azure AD **B2C** applications , while they do have a configuration setting to "Enable Implicit Flow" Yes/No (I configured "yes"), do not have a setting to enable the "ID Token" like Azure AD apps do. 

Couple of questions:

* Is this an error of this sample code, or is this sample code not supporting Azure AD B2C? 
* I noticed that the MSAL.js library linked here is older than the current available 1.1.1. I tried updating, but other issues show up in the code, so I believe this may be a breaking change. Would updating the sample to support a more recent MSAL.js library resolve the issue? 

Thank you

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
