### ISSUE TITLE
DB Could Not be Created

### ISSUE THREAD

**Issue by throwingdarts** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#27]
System.Data.SqlClient.SqlException
  HResult=0x80131904
  Message=Directory lookup for the file "D:\Projects\Sample Apps\active-directory-javascript-singlepageapp-dotnet-webapi-v2-master\TodoSPA\App_Data\TodoListServiceContext.mdf" failed with the operating system error 2(The system cannot find the file specified.).
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.
  Source=.Net SqlClient Data Provider

**Comment by yzerbroot** [comment]
Hi, I ran into the same issue, it is just the empty App_Data folder missing, just add it and it works.

**Comment by kenturley** [comment]
@yzerbroot   Thank you! Was tripping me up too. Pretty good sample app (excluding that nuance). Giving me what I need for Azure AD auth to WebApi 2.

Specifically, create this missing folder  ...\TodoSPA\App_Data  <==

**Comment by derisen** [comment]
Thank you @yzerbroot and @kenturley. Feel free to make a PR if you like, or I'll add the missing folder in the next PR

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
