### ISSUE TITLE
AADSTS50194: Application not configured as a multi-tenant application. 

### ISSUE THREAD

**Issue by Romiko** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#28]
Hi,

I am getting this error:
AADSTS50194: Application  is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

I changed this to
AccessTokenFormat = new JwtFormat(tvps, new OpenIdConnectCachingSecurityTokenProvider("https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration")),

to
AccessTokenFormat = new JwtFormat(tvps, new OpenIdConnectCachingSecurityTokenProvider("https://login.microsoftonline.com/MYTENANTID/v2.0/.well-known/openid-configuration")),

But still get an error, does this work with the latest app registration feature in AD?

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
