### ISSUE TITLE
register and configure api

### ISSUE THREAD

**Issue by sivahanuman** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#30]
Hi, i don't find steps to register and configure my asp.net web api ( expose ).

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
