### ISSUE TITLE
ida::tenant and ida::audience

### ISSUE THREAD

**Issue by thdotnet** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#5]
Hi, I was following the step-by-step but I can't figure out how to get the ida::tenant and ida::audience for the application. It's not described in the "Register the application" section. What am I missing?

**Comment by jmprieur** [comment]
Thanks for your feedback, 
Actually the tenant value is never used and doesn’t need to be set in Web.Config. (you can noticed that  “ida:Tenant” is not referenced anywhere in the code). Normally, the tenant value is used when initializing the OAuth bearer token middleware so the middleware knows what value to use for issuer validation. But all v2 based web API are currently multi-tenant, therefore, issuer validation is disabled in this sample.

As far as ida:Audience is concerned, this is the Application Id.

I've updated the README.md file (See commit [8c07990c](https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2/commit/8c07990c539bcb1aff917420b84fd055605e4c28) commit)
