### ISSUE TITLE
Getting 401 Unauthorized on api call

### ISSUE THREAD

**Issue by jared-christensen** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#6]
I followed the directions but get 401 Unauthorized when I call
http://127.0.0.1:8080/api/TodoList

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
