### ISSUE TITLE
.net core 2.0 support

### ISSUE THREAD

**Issue by MoimHossain** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#8]
The server side is based on .net framework 4.5. Many of these extension methods are not anymore avialable in .net core 2.0. Would be nice to have a sample web api running on .net core 2.0 backend. Is samples somewhere I can find (if not any plan to provide such) ? 

Nice clean sample to understand and follow, BTW. Thanks!

**Comment by jmprieur** [comment]
Thanks for your feedback
We want to update this samples. Meanwhile, I suggest you have a look at;
- an aspnetcore 2.0 WebAPI from https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore 
- and aspnet core 2.0 Web App from https://github.com/Azure-Samples/active-directory-dotnet-webapp-openidconnect-aspnetcore
- and ASP.NET core 2.0 Web app calling an asp.NET core 2.0 Web API: https://github.com/Azure-Samples/active-directory-dotnet-webapp-webapi-openidconnect-aspnetcore/tree/aspnet20 (being reviewed)

These are for the V1, but you will also find an example of a V2 web API and Web app in https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-javascriptspa and https://docs.microsoft.com/en-us/azure/active-directory/develop/guidedsetups/active-directory-aspnetwebapp. These are not ASP.NET core, but will help you finding the differences between V1 and V1.

**Comment by stpriyanka** [comment]
Is there any update for .net core 2 ?

**Comment by KalyanChanumolu-MSFT** [comment]
nothing yet for .Net Core 2?

**Comment by NicklausBrain** [comment]
If anyone managed to port this to core 2.1 please share your progress!

**Comment by MoimHossain** [comment]
Folks, I have lately seen these comments. I was able to made this work. Watching your remarks above, I have uploaded my solution into GitHub. 
https://github.com/MoimHossain/azure-ad-spa-auth-v2-net20-sample

Although, I have tried to stripped out all the irrelevant stuffs from the project, I might still left some pieces here and there. Please ignore those irrelevant part.

I think most relevant stuffs are in these two files:
https://github.com/MoimHossain/azure-ad-spa-auth-v2-net20-sample/blob/master/webapp/ClientApp/src/services/authorizationService.js

https://github.com/MoimHossain/azure-ad-spa-auth-v2-net20-sample/blob/master/webapp/Extensions/AzureAdAuthenticationBuilderExtensions.cs

Hope this helps somebody!
Thanks 

cc. @jmprieur  @stpriyanka  @Appjunkie  @NicklausBrain

**Comment by iamalexmang** [comment]
Would be fantastic to see to updates to this:
- ditch .NET Framework in favor of .NET. And please don't tell me that there are .NET Core samples, because all those samples are locked in a .NET world end-to-end, without even considering the existence of SPA frameworks such as Angular
- update it to .NET Core 3.0
Any suggestion right now would be mana.

**Comment by derisen** [comment]
Closing this as we are archiving this sample. Please check out the new sample at [ms-identity-javascript-angular-spa-aspnetcore-webapi](https://github.com/Azure-Samples/ms-identity-javascript-angular-spa-aspnetcore-webapi).
