### ISSUE TITLE
Application '<AppID>' (App Name) is not supported over the /common or /consumers endpoints

### ISSUE THREAD

**Issue by abhaybhangale** [Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#9]
Followed the instructions on the wiki, but get this error; Application ''<My App ID>" (My app Name) is not supported over the /common or /consumers endpoints. Please use the /organizations or tenant-specific endpoint.

**Comment by jmprieur** [comment]
Did you follow https://github.com/Azure-Samples/active-directory-javascript-singlepageapp-dotnet-webapi-v2#register-the-application ?
Did you register a converged app ?

**Comment by abhaybhangale** [comment]
Thanks, shortly after I reported this issue I got a few hints from a stackoverflow post and created the converged app. The sample application worked just fine with the v2.0 app.
